Refactored bash scripts

diff --git a/asc-mbp/bin/dmm-pv b/asc-mbp/bin/dmm-pv
--- a/asc-mbp/bin/dmm-pv
+++ b/asc-mbp/bin/dmm-pv
@@ -2,34 +2,36 @@
 # Download and play free PVs from DMM.R18 (dmm.co.jp)
 # Use mpv or mplayer
 
-cmd_name=$(basename "$0")
-usage="usage: $cmd_name CID"
-[ $# -ne 1 -o $1 = '-h' -o $1 = '--help' ] && { echo "$usage" >&2; exit 1; }
-cid="$1"
-url_prefix=http://cc3001.dmm.co.jp/litevideo/freepv
-url_path=${cid:0:1}/${cid:0:3}/$cid/$cid
-url_part="$url_prefix/$url_path"
-url_part=${url_part,,}
-declare -a url_suffixes=('_dmb_w.mp4' '_sm_w.mp4' '_sm_s.mp4')
-for suffix in "${url_suffixes[@]}"
-do
-    if curl -sf "${url_part}${suffix}" > /dev/null
-    then
-        url="${url_part}${suffix}"
+CMD_NAME=$(basename "$0")
+USAGE="usage: $CMD_NAME CID"
+[ $# -ne 1 -o $1 = '-h' -o $1 = '--help' ] && {
+    echo "$USAGE" >&2
+    exit 1
+}
+CID="$1"
+URL_PREFIX=http://cc3001.dmm.co.jp/litevideo/freepv
+URL_PATH=${CID:0:1}/${CID:0:3}/$CID/$CID
+URL_PART="$URL_PREFIX/$URL_PATH"
+URL_PART=${URL_PART,,}
+declare -a URL_SUFFIXES=('_dmb_w.mp4' '_sm_w.mp4' '_sm_s.mp4')
+for suffix in "${URL_SUFFIXES[@]}"; do
+    if curl -sf "${URL_PART}${suffix}" > /dev/null; then
+        URL="${URL_PART}${suffix}"
         break
     fi
 done
-[ -z $url ] && { echo 'URL is not found.' >&2; exit 1; }
+[ -z $URL ] && {
+    echo 'URL is not found.' >&2
+    exit 1
+}
 
-echo $url
-if which mpv > /dev/null
-then
-    player="mpv"
-elif which mplayer > /dev/null
-then
-    player="mplayer"
+echo $URL
+if which mpv > /dev/null; then
+    PLAYER="mpv"
+elif which mplayer > /dev/null; then
+    PLAYER="mplayer"
 else
     echo 'Neither mpv or mplayer is found in PATH.' >&2
     exit 1
 fi
-$player $url
+$PLAYER $URL
diff --git a/asc-mbp/bin/myaa b/asc-mbp/bin/myaa
--- a/asc-mbp/bin/myaa
+++ b/asc-mbp/bin/myaa
@@ -9,23 +9,23 @@
 
 export PYTHONIOENCODING="UTF-8"
 set -e
-usage='usage: myaa keyword server'
-server_dir="115dl"
-server_log="myaa.log"
-retries=3
-count=0
+USAGE='usage: myaa keyword server'
+SERVER_DIR="115dl"
+SERVER_LOG="myaa.log"
+RETRIES=3
+COUNT=0
 
 show_help() {
-   echo "$usage" >&2 
+   echo "$USAGE" >&2 
 }
 
 [ $# -ne 2 ] && { show_help; exit 1; }
 
-keyword="$1"
-server="$2"
-torrent=
-task_status=
-session_prefix="myaa"
+KEYWORD="$1"
+SERVER="$2"
+TORRENT=
+TASK_STATUS=
+SESSION_PREFIX="myaa"
 
 debug() {
     echo "INFO: $1"
@@ -35,49 +35,49 @@ debug() {
 # Download torrent using nyaa
 download_torrent() {
     debug "Searching torrent with nyaa..."
-    nyaa -p "$keyword" || exit 1
-    torrent=$(nyaa "$keyword" | sed -nE "s/.*Saved to filename '(.+)'/\1/p")
-    [ -z "$torrent" ] && {
+    nyaa -p "$KEYWORD" || exit 1
+    TORRENT=$(nyaa "$KEYWORD" | sed -nE "s/.*Saved to filename '(.+)'/\1/p")
+    [ -z "$TORRENT" ] && {
         echo 'No result.' >&2
         exit 1
     }
-    trap "{ rm '$torrent'; }" EXIT SIGINT SIGTERM
+    trap "{ rm '$TORRENT'; }" EXIT SIGINT SIGTERM
 }
 
 
 # Upload torrent using 115up
 upload_torrent() {
     debug "Uploading torrent with 115up..."
-    task_status=$(115up -t "$torrent" | grep -oE 'TRANSFERRED|BEING TRANSFERRED')
+    TASK_STATUS=$(115up -t "$TORRENT" | grep -oE 'TRANSFERRED|BEING TRANSFERRED')
     [ "$?" -ne 0 ] && {
         echo 'File not transferred. Abort.' >&2
         exit 1
     }
     while true
     do
-        [ "$task_status" = 'BEING TRANSFERRED' ] && {
+        [ "$TASK_STATUS" = 'BEING TRANSFERRED' ] && {
             echo 'Being transferred. Sleep for 15 sec ..'
             sleep 15
         } || break
         debug "Checking task status..."
-        task_status=$(115down -t | head -1 | sed -nE 's/^[0-9]+ \[(.+)\] .*/\1/p')
-        count=$((count+1)) # count=0; (( count++ )); will return 1 to cause shell exits
-        [ $count -eq $retries ] && {
-            echo 'Maximum retries is reached. Abort.' >&2
+        TASK_STATUS=$(115down -t | head -1 | sed -nE 's/^[0-9]+ \[(.+)\] .*/\1/p')
+        COUNT=$((COUNT+1)) # COUNT=0; (( COUNT++ )); will return 1 to cause shell exits
+        [ $COUNT -eq $RETRIES ] && {
+            echo 'Maximum RETRIES is reached. Abort.' >&2
             exit 1
         }
     done
 }
 
 
-# Dispatch download task to server
+# Dispatch download task to SERVER
 dispatch_task() {
-    debug "Dispatching download task to $server..."
-    session="${session_prefix}_${keyword}_$(date +%Y-%m-%d_%H:%M:%S)"
-    ssh "$server" "screen -dmS $session"
-    ssh -t "$server" "screen -S $session -p 0 -X stuff 'cd 115dl
-    echo $session >> $server_log
-    115down 1 \* |& tee -a $server_log
+    debug "Dispatching download task to $SERVER..."
+    session="${SESSION_PREFIX}_${KEYWORD}_$(date +%Y-%m-%d_%H:%M:%S)"
+    ssh "$SERVER" "screen -dmS $session"
+    ssh -t "$SERVER" "screen -S $session -p 0 -X stuff 'cd 115dl
+    echo $session >> $SERVER_LOG
+    115down 1 \* |& tee -a $SERVER_LOG
     '
     "
 }
diff --git a/asc-mbp/bin/prestige-pv b/asc-mbp/bin/prestige-pv
--- a/asc-mbp/bin/prestige-pv
+++ b/asc-mbp/bin/prestige-pv
@@ -3,39 +3,37 @@
 # Use mpv or mplayer
 # Bash 4.x required
 
-cmd_name=$(basename "$0")
-usage="usage: $cmd_name CID"
-[ $# -ne 1 -o $1 = '-h' -o $1 = '--help' ] && { echo "$usage" >&2; exit 1; }
+CMD_NAME=$(basename "$0")
+USAGE="usage: $CMD_NAME CID"
+[ $# -ne 1 -o $1 = '-h' -o $1 = '--help' ] && {
+    echo "$USAGE" >&2
+    exit 1
+}
 
-cid=${1^^}
-if ! echo $cid | grep -E '[A-Z]+-[0-9]+' > /dev/null
-then
-    if echo $cid | grep -E '[A-Z]+[0-9]+' > /dev/null
-    then
-        cid=$(echo $cid | sed 's/\([A-Z]\{1,\}\)\([0-9]\{1,\}\)$/\1-\2/')
+CID=${1^^}
+if ! echo $CID | grep -E '[A-Z]+-[0-9]+' > /dev/null; then
+    if echo $CID | grep -E '[A-Z]+[0-9]+' > /dev/null; then
+        CID=$(echo $CID | sed 's/\([A-Z]\{1,\}\)\([0-9]\{1,\}\)$/\1-\2/')
     else
-        echo 'Invalid cid format.' >&2
+        echo 'Invalid CID format.' >&2
         exit 1
     fi
 fi
 
-url="http://www.prestige-av.com/sample_movie/${cid}.wmv"
+URL="http://www.prestige-av.com/sample_movie/${CID}.wmv"
 
-if ! curl -sf "$url" > /dev/null
-then
+if ! curl -sf "$URL" > /dev/null; then
     echo 'URL is not found.' >&2
     exit 1
 fi
 
-echo $url
-if which mpv > /dev/null
-then
+echo $URL
+if which mpv > /dev/null; then
     player="mpv"
-elif which mplayer > /dev/null
-then
+elif which mplayer > /dev/null; then
     player="mplayer -aspect 16:9"
 else
     echo 'Neither mpv or mplayer is found in PATH.' >&2
     exit 1
 fi
-$player $url
+$player $URL
